### ISSUE TITLE
Autotuner aborts

### ISSUE THREAD

**Issue by jzbontar** [facebookresearch/TensorComprehensions#271]
I have a similar issue to #207.

The autotuner sometimes (3 out of 5 times) aborts due to illegal memory access when running the following Python script:

```python
import torch
import tensor_comprehensions

lang = '''
def foo(float(B, I, 2, J, F1) input, float(I, 2, J, 2, F1, F2) weight) -> (output) {
    output(b, i, j, l, f2) +=! input(b, i, k, j, f1) * weight(i, k, j, l, f1, f2)
}
'''

input = torch.Tensor(32, 128, 2, 2, 4).cuda().normal_()
weight = torch.Tensor(128, 2, 2, 2, 4, 8).cuda().normal_()
foo = tensor_comprehensions.define(lang, name='foo')
foo.autotune(input, weight)
```

The output when the autotuner breaks:

```
[WARNING]: Autotuning results won't be cached. 'cache' option is not set
[WARNING]: Using 'naive' type mapping options for autotuning. See help(your_layer.autotune) for how to set mapping options.
Generation 0    Jobs(Compiled, GPU)/total  (10, 6)/10   (best/median/worst)us: 1064/1386/1386WARNING: Logging before InitGoogleLogging() is written to STDERR
W0406 18:29:07.539638 29581 rtc.cc:199] Error at: /opt/conda/conda-bld/tensor_comprehensions_1520457708651/work/src/core/rtc.cc:199: an illegal memory access was encountered
W0406 18:29:07.539827 29581 genetic_tuning_harness.cc:431] Error at: /opt/conda/conda-bld/tensor_comprehensions_1520457708651/work/src/autotuner/genetic_tuning_harness.cc:431: an illegal memory access was encountered
F0406 18:29:07.539850 29581 genetic_tuning_harness.cc:433] [CUDA][FATAL] cuda error on gpu 0: Error at: /opt/conda/conda-bld/tensor_comprehensions_1520457708651/work/src/autotuner/genetic_tuning_harness.cc:431: an illegal memory access was encountered
tc::MappingOptions::makeNaiveMappingOptions()
    .outerScheduleFusionStrategy(tc::FusionStrategy::Preserve3Coincident)
    .outerScheduleAllowSkewing(false)
    .outerSchedulePositiveOrthant(true)
    .intraTileScheduleFusionStrategy(tc::FusionStrategy::Preserve3Coincident)
    .intraTileScheduleAllowSkewing(false)
    .intraTileSchedulePositiveOrthant(true)
    .tile(256, 32, 64, 1, 2, 4)
    .mapToThreads(1, 128)
    .mapToBlocks(2, 64)
    .unroll(8)
    .tileImperfectlyNested(false)
    .useSharedMemory(true)
    .usePrivateMemory(false)
    .unrollCopyShared(false)
    .matchLibraryCalls(true);
*** Check failure stack trace: ***
Aborted
```

**Comment by merrymercy** [comment]
I encountered the same error.

```python
conv2d_lang = """
def conv2d(float(N, C, H, W) I, float(M, C, KH, KW) W1) -> (output) {{
    output(n, m, h, w) +=! I(n, c, {sh} * h + kh, {sw} * w + kw) * W1(m, c, kh, kw)
}}
"""

The error occurs randomly for different input config.

```
[WARNING]: Autotuning results won't be cached. 'cache' option is not set
Generation 0	Jobs(Compiled, GPU)/total  (50, 50)/50   (best/median/worst)us: 151/468/34689
Generation 1	Jobs(Compiled, GPU)/total  (41, 33)/50   (best/median/worst)us: 140/216/707WARNING: Logging before InitGoogleLogging() is written to STDERR
W0408 05:35:21.780427 25400 rtc.cc:199] Error at: /home/mercy/project/TensorComprehensions/src/core/rtc.cc:199: an illegal memory access was encountered
W0408 05:35:21.780643 25400 genetic_tuning_harness.cc:431] Error at: /home/mercy/project/TensorComprehensions/src/autotuner/genetic_tuning_harness.cc:431: an illegal memory access was encountered
F0408 05:35:21.780666 25400 genetic_tuning_harness.cc:433] [CUDA][FATAL] cuda error on gpu 0: Error at: /home/mercy/project/TensorComprehensions/src/autotuner/genetic_tuning_harness.cc:431: an illegal memory access was encountered
tc::MappingOptions::makeNaiveMappingOptions()
    .outerScheduleFusionStrategy(tc::FusionStrategy::Preserve3Coincident)
    .outerScheduleAllowSkewing(false)
    .outerSchedulePositiveOrthant(true)
    .intraTileScheduleFusionStrategy(tc::FusionStrategy::Min)
    .intraTileScheduleAllowSkewing(false)
    .intraTileSchedulePositiveOrthant(true)
    .tile(4, 8, 8, 14)
    .mapToThreads(4, 16)
    .mapToBlocks(8, 256, 256)
    .unroll(1)
    .tileImperfectlyNested(false)
    .useSharedMemory(false)
    .usePrivateMemory(false)
    .unrollCopyShared(false)
    .matchLibraryCalls(true);
*** Check failure stack trace: ***
Aborted (core dumped)
```

**Comment by prigoyal** [comment]
thanks @jzbontar and @merrymercy. We are aware of such an error but didn't have a stable repro of this issue before. May I kindly request if you can retry and see if the error still happens? if it does, can you provide me the repro (i.e. update the example if there are any changes)? :)

**Comment by merrymercy** [comment]
After updating TC to the latest version, the error does not occur anymore.

**Comment by ftynse** [comment]
Latest from where?

**Comment by merrymercy** [comment]
built from https://github.com/facebookresearch/TensorComprehensions/commit/ef644ba7d638f3f8b028f52192101cf1f48b32b4

My script is more stable now. But I am not sure this issue is fixed.

**Comment by ftynse** [comment]
> The output when the autotuner breaks:

I cannot reproduce an error with these options on 4229ac4e276a6c2b6a5f92bdf29b2d26c6d6ee3a.

**Comment by ftynse** [comment]
> The output when the autotuner breaks:

I cannot reproduce an error with these options on 4229ac4e276a6c2b6a5f92bdf29b2d26c6d6ee3a.  Neither the reported options, nor the autotuner (from C++) with 25x100 options.

My machine was lax on memory errors before, so it is possible that I'm not seeing the problem.  @prigoyal and @nicolasvasilache have access to machines that were good at finding memory problems

**Comment by ftynse** [comment]
@merrymercy  for convolutions, there was a reported problem in #179, fixed by #226.  Your post does not include the sizes, so I cannot say if the fix applies to you too.

**Comment by ftynse** [comment]
@jzbontar could you please fill in the issue template with TC version, installation source, etc. ?

**Comment by jzbontar** [comment]
- OS: Ubuntu 16.04.3 LTS
- How you installed TC (docker, conda, source): conda
- Python version: Python 3.6.5
- CUDA/cuDNN version: CUDA 8.0.61, cuDNNL: 7005
- Conda version (if using conda): 4.4.11

**Comment by merrymercy** [comment]
Now the this error occurs randomly..

```
W0410 23:32:43.035991  3014 cuda_rtc.cc:44] Error at: /home/eqy2/TensorComprehensions/src/core/cuda/cuda_rtc.cc:44: CUDA_ERROR_INVALID_HANDLE
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error at: /home/eqy2/TensorComprehensions/src/core/cuda/cuda_rtc.cc:44: CUDA_ERROR_INVALID_HANDLE
Aborted (core dumped)
```

**Comment by ftynse** [comment]
@merrymercy  would you mind opening a new issue for every different observed error?

**Comment by ftynse** [comment]
Even if you don't, the error you report is very unlikely related to the one reported here.  If we prove the contrary, we will merge duplicate issues ourselves.  Otherwise, irrelevant messages only confuse the discussion and slow down the problem solving.  Please open a new issue anyway, after which I will remove all the irrelevant comments from this issue.

**Comment by ftynse** [comment]
This has gone stale
