### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by xuyufan936831611** [facebookresearch/TensorComprehensions#607]
----------------------------------------------
The  relevant information of my equipment is as follows:
- OS: Ubuntu16.04
- How you installed TC (docker, conda, source): source
- Python version: python3.6
- CUDA/cuDNN version: CUDA.0/cuDNNv5.1.5 
- Conda version (if using conda): conda 4.5.11
- GCC/GXX version (if compiling from source):GCC5.4.0
- LLVM/Tapir git hash used (if compiling from source):7.0.0svn

------------------------------------------------------------------------------------------------------------------------------------------
My problem is that I have run ”CLANG_PREFIX=$(${CONDA_PREFIX}/bin/llvm-config --prefix) ./build.sh“ and receive echo ”+ echo 'Successfully installed TC'
Successfully installed TC “,but when I run ”./test.sh“，the terminal print issues like follows：
------------------------------------------------------------------------------------------------------------------------------------------
find: `build/tc/benchmarks': 没有那个文件或目录
Running build/test/cuda/test_basic_gpu
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from BasicGpuTest
[ RUN      ] BasicGpuTest.Nvrtc
[       OK ] BasicGpuTest.Nvrtc (898 ms)
[ RUN      ] BasicGpuTest.CubReduce
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0917 09:34:01.978760 14746 test_basic_gpu.cc:92] Error at: /media/omnisky/902177fe-4ad6-4003-be5e-0f539ffb197c/xuyufan/TensorComprehensions/test/cuda/test_basic_gpu.cc:92: CUDA_ERROR_OUT_OF_MEMORY
unknown file: Failure
C++ exception with description "Error at: /media/omnisky/902177fe-4ad6-4003-be5e-0f539ffb197c/xuyufan/TensorComprehensions/test/cuda/test_basic_gpu.cc:92: CUDA_ERROR_OUT_OF_MEMORY" thrown in the test body.
[  FAILED  ] BasicGpuTest.CubReduce (823 ms)
[ RUN      ] BasicGpuTest.Restrict
[       OK ] BasicGpuTest.Restrict (540 ms)
[----------] 3 tests from BasicGpuTest (2261 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (2261 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] BasicGpuTest.CubReduce

 1 FAILED TEST
xargs: bash：以状态 255 退出；中止
------------------------------------------------------------------------------------------------------------------------------------------
In addition, when I run "python/tests/test_tc.py -v", I got the following output:
------------------------------------------------------------------------------------------------------------------------------------------
test_conv_with_backward_2kernels (__main__.TestTC) ... THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
ERROR
------------------------------------------------------------------------------------------------------------------------------------------
So I just want to know whether the issue is caused by the only one piece of GPU?

**Comment by ftynse** [comment]
It seems that Your GPU does not have enough memory to run some of the
tests. Although I am surprised it is on CUBreduce.

**Comment by xuyufan936831611** [comment]
I'm sorry to disturb you again.
My GPU is NVIDIA GeForce GTX 1080 Ti, and the total memory is 10.91GiB. Then I just run the following simple test:
----------------------------------------------------------------------------------------------------------------------------------------------
import torch
import tensor_comprehensions as tc
tc_str = """
def relu(float(B,M) I) -> (O) {
    O(b, m) = fmax(I(b, m), 0)
}
"""
T = tc.define(tc_str, tc.make_naive_options_factory())
O = T.relu(torch.randn(100, 128, device='cuda'))
----------------------------------------------------------------------------------------------------------------------------------------------
And I got runtime error as follows:
----------------------------------------------------------------------------------------------------------------------------------------------
/home/omnisky/anaconda2/envs/xuyufan/bin/python3.6 /media/omnisky/902177fe-4ad6-4003-be5e-0f539ffb197c/xuyufan/dpp-master/DPPinPytorch/test_tc.py
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
Traceback (most recent call last):
  File "/media/omnisky/902177fe-4ad6-4003-be5e-0f539ffb197c/xuyufan/dpp-master/DPPinPytorch/test_tc.py", line 9, in <module>
    O = T.relu(torch.randn(100, 128, device='cuda'))
  File "/home/omnisky/anaconda2/envs/xuyufan/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/THCTensorRandom.cu:25
----------------------------------------------------------------------------------------------------------------------------------------------
So I wonder if there are other reasons?

**Comment by xuyufan936831611** [comment]
Thank you very much, now it works normally!
